### ISSUE TITLE
Running the Script on Windows

### ISSUE THREAD

**Issue by MomenFathi** [rezasp/vbscan#8]
After Running the code on windows

cmd> perl vbscan.pl 

it returns :- 
Undefined subroutine &main::tprint called at "PATH"\vbscan.pl line 76

**Comment by rezasp** [comment]
Fixed ;)
use new version , test it , enjoy

**Comment by MomenFathi** [comment]
thanx , i tried the new version but .. still the same problem ! 
Undefined subroutine &main::tprint called at \vbscan.pl line 76

**Comment by rezasp** [comment]
[vbtest.zip](https://github.com/rezasp/vbscan/files/123897/vbtest.zip)

Please test it , and give me your result !

**Comment by MomenFathi** [comment]
That's what it Return 

C:\Users\Downloads\vbtest>perl vbscan.pl
←[33mYour Report : reports/.txt

←[0m

**Comment by Laggii** [comment]
I fixed it by myself on windows, you can see the changes here: https://github.com/Laggii/vbscan/commit/e90f53d366e0f93033eb381b2a6a42667b63cad0

Now its correctly logging data in file

**Comment by rezasp** [comment]
check new relaese

**Comment by rezasp** [comment]
Thanks to Laggii
issue fixed
check it
